### ISSUE TITLE
Codelab Does Not Build: ClassNotFoundException: javax.xml.bind.JAXBException

### ISSUE THREAD

**Issue by alonalbert** [googlecodelabs/kotlin-coroutines#113]
```
Android Studio 4.2 Canary 15
Build #AI-202.7660.26.42.6922807, built on October 22, 2020
Runtime version: 11.0.8+0-b944-P17168821 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 5.7.17-1rodete4-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8

Current Desktop: X-Cinnamon
```

```
Executing tasks: [:start:assembleDebug, :finished_code:assembleDebug] in project /home/aalbert/src/kotlin-coroutines/advanced-coroutines-codelab

> Task :start:preBuild UP-TO-DATE
> Task :start:preDebugBuild UP-TO-DATE
> Task :sunflower:preBuild UP-TO-DATE
> Task :sunflower:preDebugBuild UP-TO-DATE
> Task :sunflower:compileDebugAidl NO-SOURCE
> Task :start:compileDebugAidl NO-SOURCE
> Task :sunflower:packageDebugRenderscript NO-SOURCE
> Task :start:compileDebugRenderscript NO-SOURCE
> Task :start:checkDebugManifest
> Task :start:generateDebugBuildConfig
> Task :start:prepareLintJar UP-TO-DATE
> Task :start:prepareLintJarForPublish UP-TO-DATE
> Task :start:generateDebugSources
> Task :start:dataBindingExportBuildInfoDebug
> Task :sunflower:checkDebugManifest
> Task :sunflower:compileDebugRenderscript NO-SOURCE
> Task :sunflower:generateDebugBuildConfig
> Task :sunflower:prepareLintJar UP-TO-DATE
> Task :sunflower:prepareLintJarForPublish UP-TO-DATE
> Task :sunflower:generateDebugSources
> Task :sunflower:dataBindingExportBuildInfoDebug
> Task :sunflower:dataBindingMergeDependencyArtifactsDebug
> Task :sunflower:generateDebugResValues
> Task :sunflower:generateDebugResources
> Task :sunflower:packageDebugResources
> Task :sunflower:dataBindingMergeGenClassesDebug
> Task :sunflower:dataBindingGenBaseClassesDebug
> Task :sunflower:processDebugManifest
> Task :start:dataBindingMergeGenClassesDebug
> Task :sunflower:parseDebugLibraryResources
> Task :start:generateDebugResValues
> Task :start:generateDebugResources
> Task :sunflower:generateDebugRFile
> Task :sunflower:kaptGenerateStubsDebugKotlin

> Task :sunflower:kaptDebugKotlin FAILED
e: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	at org.jetbrains.kotlin.cli.jvm.plugins.ServiceLoaderLite.loadImplementations(ServiceLoaderLite.kt:51)
	at org.jetbrains.kotlin.cli.jvm.plugins.ServiceLoaderLite.loadImplementations(ServiceLoaderLite.kt:44)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension$loadProcessors$efficientProcessorLoader$1.doLoadProcessors(Kapt3Extension.kt:83)
	at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.loadProcessors(ProcessorLoader.kt:45)
	at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.loadProcessors$default(ProcessorLoader.kt:28)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.loadProcessors(Kapt3Extension.kt:88)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:171)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:98)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:97)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:82)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:557)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:82)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:548)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:177)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1558)
	at jdk.internal.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 42 more


> Task :start:mergeDebugResources
> Task :start:dataBindingExportFeaturePackageIdsDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sunflower:kaptDebugKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
24 actionable tasks: 20 executed, 4 up-to-date

```

**Comment by alonalbert** [comment]
Fixed with:
```
Index: advanced-coroutines-codelab/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- advanced-coroutines-codelab/build.gradle    (revision 1d307f00b4f6b2398ceaaae1a5f062bc128c9dfe)
+++ advanced-coroutines-codelab/build.gradle    (date 1604762139614)
@@ -1,13 +1,13 @@
 // Top-level build file where you can add configuration options common to all sub-projects/modules.
 
 buildscript {
-    ext.kotlin_version = '1.3.50'
+    ext.kotlin_version = '1.4.10'
 
     ext {
 
         // global variables
         compile_sdk_version = 29
-        kotlin_version = '1.3.60'
+        kotlin_version = '1.4.10'
         min_sdk_version = 21
 
         // local variables (use def)
@@ -108,7 +108,7 @@
         jcenter()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:3.5.2'
+        classpath 'com.android.tools.build:gradle:4.1.0'
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files

```

[Fix_https___github_com_googlecodelabs_kotlin-coroutines_issues_113.patch.zip](https://github.com/googlecodelabs/kotlin-coroutines/files/5504957/Fix_https___github_com_googlecodelabs_kotlin-coroutines_issues_113.patch.zip)

**Comment by wojtek-kalicinski** [comment]
I'm updating dependencies in a pull request now, thanks for the report.
