### ISSUE TITLE
Calling DAO on main thread issue.

### ISSUE THREAD

**Issue by RobinCaroff** [googlecodelabs/kotlin-coroutines#6]
Hi,

The project crashes with an IllegalStateException when calling `titleDao.insertTitle(Title(result))` in the `refreshTitle()' method.

It happens because even if it is called inside the `withContext(Dispatchers.IO)` block, the result of the `fetchNewWelcome`call is dispatched on the main thread by the uiHandler.

Wrapping only the `titleDao.insertTitle(Title(result))` call inside the withContext block will fix it :
```
try {
            val result = network.fetchNewWelcome().await()
            withContext(Dispatchers.IO) {
                titleDao.insertTitle(Title(result))
            }
        } catch (error: FakeNetworkException) {
            throw TitleRefreshError(error)
        }
```

You could also remove the uiHandler from the FakeNetworkLibrary. I actually don't think the repository should know/care about the UI thread.

CRASH LOG:

> 2018-10-08 18:26:04.773 17736-17736/com.example.android.kotlincoroutines E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.android.kotlincoroutines, PID: 17736
>     java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
>         at android.arch.persistence.room.RoomDatabase.assertNotMainThread(RoomDatabase.java:204)
>         at android.arch.persistence.room.RoomDatabase.beginTransaction(RoomDatabase.java:251)
>         at com.example.android.kotlincoroutines.main.TitleDao_Impl.insertTitle(TitleDao_Impl.java:45)
>         at com.example.android.kotlincoroutines.main.TitleRepository$refreshTitle$2.invokeSuspend(TitleRepository.kt:67)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
>         at kotlin.coroutines.experimental.migration.ExperimentalContinuationMigration.resume(CoroutinesMigration.kt:76)
>         at kotlin.coroutines.experimental.SafeContinuation.resume(SafeContinuationJvm.kt:46)
>         at com.example.android.kotlincoroutines.main.TitleRepositoryKt$await$2$1.invoke(TitleRepository.kt:93)
>         at com.example.android.kotlincoroutines.main.TitleRepositoryKt$await$2$1.invoke(Unknown Source:2)
>         at com.example.android.kotlincoroutines.util.FakeNetworkCall$trySendResult$$inlined$let$lambda$1.run(FakeNetworkLibrary.kt:146)
>         at android.os.Handler.handleCallback(Handler.java:790)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6494)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by RobinCaroff** [comment]
I needed to change the compiler to "Early Access Preview 1.3". Strange that the withContext behaviour changed.
